<a href="https://colab.research.google.com/github/irythmgarg/Implementation_of_SKlearn_Simple_Linear_Regression_Model/blob/main/Implementation_of_Simple_Linear_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPLEMENTATION OF SIMPLE LINEAR REGRESSION**

In [59]:
import pandas as pd # import pandas
import numpy as np #import numpy


In [60]:
df=pd.read_csv('/content/placement 2.csv'); # dataset of cgpa and placement
df.head();

In [82]:
x=df.iloc[:,0].values;  # cgpa column
y=df.iloc[:,1].values;  # placement column

In [77]:
df.shape # number of row and columns

(200, 2)

In [83]:
from sklearn.model_selection import train_test_split # spliting of dataset into training and testig part
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
y_train

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [92]:
from sklearn.linear_model import LinearRegression #  inbuilt model  scikit learn class
lr=LinearRegression() # object of class
x_train_pd=pd.DataFrame(x_train);
x_test_pd=pd.DataFrame(x_test);
lr.fit(x_train,y_train)

In [93]:
y_pred=lr.predict(x_test_pd); # prediction of test data

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [94]:
pd.DataFrame(y_pred).head() # result of prediction

0
0  3.891116
1  3.093245
2  2.384646
3  2.574349
4  1.653729

# This the class made by us to understand working of inbuilt scikit learn Linear regression class

In [86]:
class OurLinearRegression :
  def __init__(self):
    self.m=None # slope of the minimum error line
    self.b=None; # intercept of the line
  def fit(self,x_train,y_train):
    num=0;
    den=0;
    for i in range(x_train.shape[0]):
       num+=(x_train[i]-x_train.mean())*(y_train[i]-y_train.mean());
       den+=(x_train[i]-x_train.mean())**2;
    self.m=num/den;
    self.b=y_train.mean()-self.m*x_train.mean();
  def predict(self,x_test):
    return self.m*x_test+self.b;


In [95]:
mylr=OurLinearRegression() # our model object
mylr.fit(x_train,y_train)

In [90]:
y_test #actual values

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [106]:
mylr.predict(x_test) # our prediction

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

In [104]:
pd1 = pd.DataFrame({
    'Our_class_prediction': mylr.predict(x_test),
    'Actual': y_test,
    'Scikitlearn_class_prediction': y_pred
})

You can see that our prediction and that of class is exactly same

In [105]:
pd1

Our_class_prediction  Actual  Scikitlearn_class_prediction
0               3.891116    4.10                      3.891116
1               3.093245    3.49                      3.093245
2               2.384646    2.08                      2.384646
3               2.574349    2.33                      2.574349
4               1.653729    1.94                      1.653729
5               1.776478    1.48                      1.776478
6               2.072193    1.86                      2.072193
7               2.931439    3.09                      2.931439
8               3.762787    4.21                      3.762787
9               2.937018    2.87                      2.937018
10              4.091979    3.65                      4.091979
11              3.511709    4.00                      3.511709
12              2.970495    2.89                      2.970495
13              2.401384    2.60                      2.401384
14              3.188097    2.99                      3.188097
15              3.467073    3.25                      3.467073
16              1.943864    1.86                      1.943864
17              3.243892    3.67                      3.243892
18              2.976075    2.37                      2.976075
19              3.416857    3.42                      3.416857
20              2.557611    2.48                      2.557611
21              3.165778    3.65                      3.165778
22              2.858905    2.60                      2.858905
23              3.121142    2.83                      3.121142
24              3.684674    4.08                      3.684674
25              2.870064    2.56                      2.870064
26              3.494970    3.58                      3.494970
27              3.344323    3.81                      3.344323
28              3.919014    4.09                      3.919014
29              1.960602    2.01                      1.960602
30              3.651197    3.63                      3.651197
31              3.210415    2.92                      3.210415
32              3.740469    3.51                      3.740469
33              2.786371    1.94                      2.786371
34              2.780792    2.21                      2.780792
35              3.271789    3.34                      3.271789
36              3.528447    3.34                      3.528447
37              2.613406    3.23                      2.613406
38              2.658042    2.01                      2.658042
39              2.713837    2.61                      2.713837